---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    secret: {{ my.name }}
  name: {{ my.name }}
  namespace: {{ app.namespace }}
data:
  {% for key in strukt.get("vars", []) %}
    {% if strukt.vars[key] %}
    {{key}}: {{ strukt.vars[key] | b64encode  }}
    {% else %}
    {{key}}: ""  # TODO: what is best strategy for empty values?
    {% endif %}
  {% endfor %}
  {% for key in strukt.get("files", []) %}
    {{key}}: {{ my.load_file(strukt.files[key])  | b64encode }}
  {% endfor %}
