apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
{% for res in app.resources %}
- {{ res.filename }}
{% endfor %}
namespace: {{ app.namespace }}

patches:
{% for res in app.resources %}
{% for pat in res.patches %}
- {{ pat.filename }}
{% endfor %}
{% endfor %}


configMapGenerator:
{% for cm in my.configmaps %}
- name: {{ cm.name }}
  options:
    labels:
      config-map: {{ cm.name }}
  literals:
{% for key in cm.vars %}
    - {{ key }}={{ cm.vars[key] }}
{% endfor %}
{% endfor %}
