apiVersion: apps/v1
kind: {{ target.kind }}
metadata:
  name: {{ target.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ config.containers[0].name }}
        startupProbe:
          initialDelaySeconds: {{ config.containers[0].startupProbe.delay | default(10) }}
          periodSeconds: {{ config.containers[0].startupProbe.period | default(2) }}
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: {{ config.containers[0].startupProbe.tries | default(30) }}
          httpGet:
            scheme: HTTP
            path: {{ config.containers[0].startupProbe.httpGet.path }}
            port: 8080
            #httpHeaders:
            #- name: Authorization
            #  value: Basic $(printf "%s:%s" $STARTUP_PROBE_USR $STARTUP_PROBE_PSW | base64)
        readinessProbe:
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          httpGet:
            scheme: HTTP
            path: {{ config.containers[0].readinessProbe.httpGet.path }}
            port: 8080
            #httpHeaders:
            #- name: Authorization
            #  value: Basic $(printf "%s:%s" $READINESS_PROBE_USR $READINESS_PROBE_PSW | base64)
        livenessProbe:
          periodSeconds: 2
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
          httpGet:
            scheme: HTTP
            path: {{ config.containers[0].livenessProbe.httpGet.path }}
            port: 8080
            #httpHeaders:
            #- name: Authorization
            #  value: Basic $(printf "%s:%s" $LIVENESS_PROBE_USR $LIVENESS_PROBE_PSW | base64)
