---
apiVersion: apps/v1
kind: {{ target.kind }}
metadata:
  name: {{ target.name }}
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: {{ cfg.selector_key }}
                    operator: In
                    values:
                      - {{ app.name }}
              topologyKey: "kubernetes.io/hostname"
