team: devteam1
env: dev

replicas: 1

services:
  ports:
    http:
      protocol: TCP
      port: 8080
      targetPort: 8080

containers:
  app:
    name: app
    imagePullPolicy: Always
    ports:
    - containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 1
        memory: 512M
      requests:
        cpu: 200m
        memory: 512M
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 30
      httpGet:
        scheme: HTTP
        path: actuator/info
        port: 8080
    readinessProbe:
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      httpGet:
        scheme: HTTP
        path: actuator/info
        port: 8080
    livenessProbe:
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
      httpGet:
        scheme: HTTP
        path: actuator/info
        port: 8080
