# this is a default file. It does not define any toplevel Objects

default:
  HttpProbesPatch:
    name: app
    startupProbe:
      initialDelaySeconds: 10
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 30
      httpGet:
        scheme: HTTP
        path: actuator/info
        port: 8080
    readinessProbe:
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 1
      httpGet:
        scheme: HTTP
        path: actuator/info
        port: 8080
    livenessProbe:
      periodSeconds: 2
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 3
      httpGet:
        scheme: HTTP
        path: actuator/info
        port: 8080

  PodDisruptionBudget:
    minAvailable: 1

  AntiAffinityPatch:
    selector_key: app

  Deployment:
    name: app
    imagePullPolicy: Always
    port:
      containerPort: 8080
      protocol: TCP
    resources:
      limits:
        cpu: 1
        memory: 512M
      requests:
        cpu: 200m
        memory: 512M
