---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ my.name }}
spec:
  replicas: {{ cfg.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ my.name }}
  template:
    metadata:
      name: {{ my.name }}
      labels:
        app: {{ my.name }}
      annotations:
        app.kubernetes.io/name: {{ my.name }}
        app.kubernetes.io/version: "{{ cfg.version }}"
        app.kubernetes.io/component: webservice
        app.kubernetes.io/part-of: {{ cfg.project }}
        app.kubernetes.io/managed-by: kustomize
        co.elastic.logs/enabled: "true"
        co.elastic.logs/exclude_lines: DEBUG
    spec:
      #restartPolicy: Never
      containers:
      - name: {{ default.name }}
        image: {{ cfg.image_repo }}/{{ app.name }}.app:{{ cfg.version }}
        imagePullPolicy: {{ default.imagePullPolicy }}
        envFrom:
        - secretRef:
        {% for secr in cfg.get("secret-vars",[]) %}
            name: {{ secr }}
        {% endfor %}
        - configMapRef:
        {% for cm in cfg.get("vars",[]) %}
            name: {{ cm }}
        {% endfor %}
        ports:
        - containerPort: {{ default.port.containerPort }}
          protocol: {{ default.port.protocol }}
        resources:
          limits:
            cpu: {{ default.resources.limits.cpu }}
            memory: {{ default.resources.limits.memory }}
          requests:
            cpu: {{ default.resources.requests.cpu }}
            memory: {{ default.resources.requests.memory }}
