---
apiVersion: apps/v1
kind: {{ target.kind }}
metadata:
  name: {{ target.name }}
spec:
  template:
    spec:
      containers:
      - name: {{ default.name }}
        startupProbe:
          initialDelaySeconds: {{ default.startupProbe.initialDelaySeconds }}
          periodSeconds: {{ default.startupProbe.periodSeconds }}
          timeoutSeconds: {{ default.startupProbe.timeoutSeconds }}
          successThreshold: {{ default.startupProbe.successThreshold }}
          failureThreshold: {{ default.startupProbe.failureThreshold }}
          httpGet:
            scheme: {{ default.startupProbe.httpGet.scheme }}
            path: {{ default.startupProbe.httpGet.path }}
            port: {{ default.startupProbe.httpGet.port }}
        readinessProbe:
          periodSeconds: {{ default.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ default.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ default.readinessProbe.failureThreshold }}
          successThreshold: {{ default.readinessProbe.successThreshold }}
          httpGet:
            scheme: {{ default.readinessProbe.httpGet.scheme }}
            path: {{ default.readinessProbe.httpGet.path }}
            port: {{ default.readinessProbe.httpGet.port }}
        livenessProbe:
          periodSeconds: {{ default.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ default.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ default.livenessProbe.failureThreshold }}
          successThreshold: {{ default.livenessProbe.successThreshold }}
          httpGet:
            scheme: {{ default.livenessProbe.httpGet.scheme }}
            path: {{ default.livenessProbe.httpGet.path }}
            port: {{ default.livenessProbe.httpGet.port }}
