---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ app.namespace }}

resources:
{% for res in my.resources() %}
- {{ res.filename }}
{% endfor %}

patches:
{% for pat in my.patches() %}
- {{ pat.filename }}
{% endfor %}

configMapGenerator:
{% for cm in my.konfig_maps() %}
- name: {{ cm.name }}
  options:
    labels:
      config-map: {{ cm.name }}
  literals:
    {% for key in cm.yaml.literals %}
     - {{ key }}={{ cm.yaml.literals[key] }}
    {% endfor %}
{% endfor %}
