---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ app.namespace }}

resources:
{% for res in app.resources %}
- {{ res.filename }}
{% endfor %}

patches:
{% for res in app.resources %}
{% for pat in res.patches %}
- {{ pat.filename }}
{% endfor %}
{% endfor %}

configMapGenerator:
{% for cm in app.kust_resources %}
- name: {{ cm.name }}
  options:
    labels:
      config-map: {{ cm.name }}
  literals:
{% for key in cm.yaml.literals %}
    - {{ key }}={{ cm.yaml.literals[key] }}
{% endfor %}
{% endfor %}
