---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ app.namespace }}

resources:
{% for res in my.get_resources() %}
- {{ res.filename }}
{% endfor %}

patches:
{% for pat in my.get_patches() %}
- {{ pat.filename }}
{% endfor %}

configMapGenerator:
{% for cm in app.kust_resources %}
- name: {{ cm.name }}
  options:
    labels:
      config-map: {{ cm.name }}
  literals:
{% for key in cm.yaml["data"] %}
     - {{ key }}={{ cm.yaml["data"][key] }}
{% endfor %}
{% endfor %}
