---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ my.name }}
spec:
  # This can be set from python code
  minAvailable: {{ cfg.get("minAvailable", 1) }} # TODO: use `cfg.attr or 1`  instead of get
  selector:
    matchLabels:
      app: {{ app.name }}
