---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ my.name }}
spec:
  # This can be set from python code
  minAvailable: {{ cfg.minAvailable | default(1) }} # TODO: use defaults from config
  selector:
    matchLabels:
      app: {{ app.name }}
