---
kind: Service
apiVersion: v1
metadata:
  name: {{ my.name }}
  labels:
    app: {{ app.appname }}
spec:
  selector:
    app: {{ app.appname }}
  ports:
{% for port in strukt.get("ports", [{"name": "http"}]) %}
  - protocol: TCP
    port: {{ port.port | default(default.servicePort) }}
    targetPort: {{ port.targetPort | default(default.containerPort) }}
    name: {{ port.name | default("http") }}
{% endfor %}
