---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: {{ app.namespace }}

resources:
{% for res in my.resources() %}
- {{ res.filename }}
{% endfor %}

patches:
{% for pat in my.patches() %}
- {{ pat.filename }}
{% endfor %}

configMapGenerator:
{% for cm in konf.get("config_maps",{}).keys()  %}
- name: {{ cm }}
  options:
    labels:
      config-map: {{ cm }}
  literals:
    {% for varname in konf.config_maps[cm].get("vars",{}).keys() %}
     - {{ varname }}={{ konf.config_maps[cm].vars[varname ] }}
    {% endfor %}
  files:
    {% for filename in konf.config_maps[cm].get("files",[]) %}
     - {{ filename }}
    {% endfor %}
{% endfor %}
