apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []

namespace: {{ env.namespace }}

patches: []

configMapGenerator:
- name: {{ app.name }}-vars
  options:
    labels:
      config-map: {{ app.name }}-vars
  literals: []
